const checklistData = [
  {
    title: "Profit & Loss",
    anchor: "#profit-loss",
    items: [
      {
        name: "Revenue growth YoY & QoQ",
        description: "Look for consistent revenue growth both year-over-year (YoY) and quarter-over-quarter (QoQ). Strong growth signifies increasing demand, market expansion, and product/service acceptance."
      },
      {
        name: "EBITDA margin trend",
        description: "Check the trend of EBITDA margins over time. A stable or increasing margin indicates good operational efficiency and effective cost management."
      },
      {
        name: "Net Profit margin sustainability",
        description: "Assess whether the company’s net profit margin is sustainable. A high and stable margin suggests profitability and efficient cost management."
      }
    ]
  },
  {
    title: "Balance Sheet",
    anchor: "#balance-sheet",
    items: [
      {
        name: "Debt-to-equity ratio",
        description: "The ratio indicates the level of a company’s debt relative to equity. A high ratio may indicate financial risk, whereas a low ratio suggests a more conservative approach to debt."
      },
      {
        name: "Current ratio",
        description: "The current ratio shows a company's ability to pay short-term liabilities with its short-term assets. A ratio above 1 is typically considered healthy, indicating liquidity."
      },
      {
        name: "Cash reserves",
        description: "Check the company’s cash reserves. Higher cash reserves ensure the company can weather economic downturns or fund growth opportunities."
      }
    ]
  },
  {
    title: "Cash Flow",
    anchor: "#cash-flow",
    items: [
      {
        name: "Free Cash Flow generation",
        description: "Free cash flow is the cash generated by the company after paying for capital expenditures. Positive free cash flow is a good indicator of financial health and the ability to reinvest in the business."
      },
      {
        name: "CapEx vs OCF",
        description: "Compare capital expenditures (CapEx) to operating cash flow (OCF). A high CapEx relative to OCF could indicate heavy investment in future growth, but also increased short-term cash outflow."
      },
      {
        name: "Operating cash flow trend",
        description: "Look for trends in operating cash flow. Consistently positive OCF means the business is generating cash from its core operations and not relying on external financing."
      }
    ]
  }
];

const container = document.createElement('div');
container.innerHTML = `
  <style>
    .checklist-section {
      padding: 10px 0;
      font-family: sans-serif;
    }
    .checklist-section h4 {
      margin: 0 0 5px 0;
      font-size: 16px;
    }
    .checklist-section a {
      font-weight: bold;
      text-decoration: none;
      color: #0056b3;
    }
    .checklist-items {
      list-style: none;
      padding-left: 20px;
    }
    .checklist-items li::before {
      content: "✓";
      margin-right: 5px;
      color: green;
    }
    .description {
      font-size: 14px;
      color: #555;
      margin-top: 5px;
    }
  </style>
`;

checklistData.forEach(section => {
  const sectionDiv = document.createElement('div');
  sectionDiv.className = 'checklist-section';

  const titleLink = document.createElement('a');
  titleLink.href = section.anchor;
  titleLink.textContent = section.title;

  const header = document.createElement('h4');
  header.appendChild(titleLink);
  sectionDiv.appendChild(header);

  const ul = document.createElement('ul');
  ul.className = 'checklist-items';

  section.items.forEach(item => {
    const li = document.createElement('li');
    li.textContent = item.name;

    const description = document.createElement('div');
    description.className = 'description';
    description.textContent = item.description;
    
    li.appendChild(description);
    ul.appendChild(li);
  });

  sectionDiv.appendChild(ul);
  container.appendChild(sectionDiv);
});

window.setDrawerContent(container);
